name: Build Resource Pack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r release.zip *
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
